### ISSUE TITLE
Mimic rrule.js in toText()

### ISSUE THREAD

**Issue by magpiedigital** [JonasWanke/rrule#10]
**Describe the bug**

The toText() function of this package has different outputs than the toText() function in `rrule.js`. 

e.g. this package - 'Weekly on Monday'
       rrule.js - 'every week on Monday'

For my uses, this is an obvious UX bug and my only solution is to do things on the server using rrule.js. Ideally, this package would have the same toText() output as `rrule.js`

**Environment:**

- Package version:  0.1.1

**Comment by JonasWanke** [comment]
This package intentionally uses a different algorithm for converting RRULEs to text, with the goal of supporting more options and creating text that is easier to understand by users.

You can create a PR that offers an [<kbd>rrule.js</kbd>](https://github.com/jakubroztocil/rrule)-like [`toText`](https://github.com/jakubroztocil/rrule/blob/master/src/nlp/totext.ts) implementation in addition to what is currently offered, but I currently don't have the time for doing so and compatibility with [<kbd>rrule.js</kbd>](https://github.com/jakubroztocil/rrule) isn't a goal of this package.

**Comment by magpiedigital** [comment]
That's understandable, and I do think your text is better overall, just more convenient to use rrulejs on the serv. I guess an ideal feature would be customising the toText function without having to do a PR. Just a thought. Cheers!
