### ISSUE TITLE
No way to clear until and count in RecurrenceRule

### ISSUE THREAD

**Issue by pauldemarco** [JonasWanke/rrule#17]
**Describe the bug**
Unable to clear **count** and **until** fields of RecurrenceRule, since copyWith will ignore null values passed in.

Workaround is to create a new RecurrenceRule and pass in the parameters.

Solution could be adding .clearUntil and .clearCount methods.

**Environment:**
- Package version:  0.1.2

**Comment by pauldemarco** [comment]
Also needed for bySetPositions since passing an empty set leads to error.

**Comment by JonasWanke** [comment]
`recurrenceRule.copyWith(…)` now has three additional parameters: `clearUntil`/`clearCount`/`clearInterval`. This is published as part of [v0.1.3](https://github.com/JonasWanke/rrule/releases/tag/v0.1.3).

I'm not sure about your second comment about `bySetPositions`. Could you please provide some example code where this happens?
