### ISSUE TITLE
migrate this package to dart sound null safety

### ISSUE THREAD

**Issue by xiaozhizhong** [JonasWanke/rrule#18]
Any plan migrate this package to dart sound null safety?

**Comment by JonasWanke** [comment]
Yes! I've just started working on that yesterday, though I don't yet know when I'll be done. As part of this migration, I'm also getting rid of `time_machine` as a dependency, addressing #9 and #16.

**Comment by JonasWanke** [comment]
The migration is done and published as part of [v0.2.0](https://github.com/JonasWanke/rrule/releases/tag/v0.2.0)!
