### ISSUE TITLE
No warning for creating a RRULE with BYWEEKNO, but with non-YEARLY frequency

### ISSUE THREAD

**Issue by bogpie** [JonasWanke/rrule#19]
*Describe the bug*
I previously created an RRULE for an event, which used BYWEEKNO, and the frequency was DAILY. 

This is for a project in which events should be exported from a local timetable to Google Calendar. I was surprised to see that, despite the fact that events are added accordingly, I couldn't edit them on my phone. 

After reverse-engineering the problem, I realized that it was related to the BYWEEKNO field. Then I found out that, according to [RFC5545](https://tools.ietf.org/html/rfc5545#page-42), BYWEEKNO "MUST NOT be used when the FREQ rule part is set to anything other than YEARLY." ([here](https://groups.google.com/g/google-rfc-2445/c/mvW2boE2XeE?pli=1) is a useful discussion on this subject, which I have found while looking for the problem).

Therefore, it would be useful if this package reported an error when a RRULE doesn't respect this standard.

*Environment:*
- Package version: 0.1.2

**Comment by JonasWanke** [comment]
Thanks for pointing out this bug and even referencing the relevant part of the RFC! I've just published [v0.2.1](https://pub.dev/packages/rrule/changelog#v021--2021-04-26) with a fix for this.
