### ISSUE TITLE
Unable to add events to Google Calendar without 'Z' suffix in UNTIL's time of rrule 

### ISSUE THREAD

**Issue by bogpie** [JonasWanke/rrule#21]
**Describe the bug**
I am trying to import events from a local calendar to Google Calendar. 
Here are some examples:

```
RRULE:FREQ=YEARLY;UNTIL=20210605T000000;INTERVAL=1;BYDAY=WE;BYWEEKNO=3,9,11,13,15,17,19,21,41,43,45,47,49,51

RRULE:FREQ=YEARLY;UNTIL=20210605T000000;INTERVAL=1;BYDAY=WE;BYWEEKNO=2,4,10,12,14,16,18,20,22,42,44,46,48,50
 ```

The error encountered is 
`DetailedApiRequestError(status: 400, message: Invalid recurrence rule.)`

A fix I found was replacing the time data inside the "UNTIL" field, it is "T000000" here, with an "T000000Z", as below:

```
RRULE:FREQ=YEARLY;UNTIL=20210605T000000Z;INTERVAL=1;BYDAY=WE;BYWEEKNO=3,9,11,13,15,17,19,21,41,43,45,47,49,51

RRULE:FREQ=YEARLY;UNTIL=20210605T000000Z;INTERVAL=1;BYDAY=WE;BYWEEKNO=2,4,10,12,14,16,18,20,22,42,44,46,48,50
```

I implemented this fix after finding this paragraph in [RFC5545](https://tools.ietf.org/html/rfc5545#page-34):
>       The date with UTC time, or absolute time, is identified by a LATIN
>       CAPITAL LETTER Z suffix character, the UTC designator, appended to
>       the time value.  For example, the following represents January 19,
>       1998, at 0700 UTC:

**Environment:**

- Package version: 0.1.2

**Comment by JonasWanke** [comment]
This is already possible by using an encoder directly:

```dart
RecurrenceRuleToStringEncoder(options: RecurrenceRuleToStringOptions(isTimeUtc: true))
  .convert(myRecurrenceRule)
```

As that's quite hidden, I've just published [v0.2.2](https://pub.dev/packages/rrule/changelog#v022--2021-04-28) making this feature more visible by directly accepting those options in `toString(…)`. Now, you can just call:

```dart
myRecurrenceRule.toString(options: RecurrenceRuleToStringOptions(isTimeUtc: true))
```
