### ISSUE TITLE
using DateTime instead of LocalDateTime[non null-safety]

### ISSUE THREAD

**Issue by loicgeek** [JonasWanke/rrule#23]
Hi, My project was created 1year ago, I cannot yet migrate to null-safety, is there a way to use the latest version without null-safe?

**Comment by JonasWanke** [comment]
AFAIK you can just depend on it like on any other version. (But you won't get the advantages of null-safe types until you migrate your project to target a null-safe Dart version.)

**Comment by loicgeek** [comment]
@JonasWanke depending on 2 * version of rrule plugin throws error due to unsatisfied dependency.

**Comment by JonasWanke** [comment]
@loicgeek Which dependency is unsatisfied? Can you show me the error message?

**Comment by loicgeek** [comment]
@JonasWanke  ```
Because [project] depends on rrule >=0.2.0 which requires SDK version >=2.12.0 <3.0.0, version solving failed.
pub get failed (1; Because [project] depends on rrule >=0.2.0 which requires SDK version >=2.12.0 <3.0.0, version solving failed.)
exit code 1
```

**Comment by JonasWanke** [comment]
@loicgeek It looks like your installed Dart version is < 2.12.0. You could try installing a more recent version (≥ 2.12.0) – as long as the `environment` section of your project's `pubspec.yaml` is not set to `>=2.12.0` (or higher), the project will still not use null-safety:

```yaml
environment:
  sdk: '>=2.10.0 <3.0.0'
```

**Comment by loicgeek** [comment]
@JonasWanke  I actually don't want to use null safety, If I upgrade my Flutter version, the project would not works anymore

**Comment by JonasWanke** [comment]
@loicgeek AFAIK you can upgrade the Flutter SDK without actually opting into null-safety. But if that's not an option for you, I'm afraid there's no other way to use the latest version of this package.

**Comment by loicgeek** [comment]
@JonasWanke  hummm...so I have to migrate to null safety, sad!
