### ISSUE TITLE
Generating date with count parameter for the same day return unexpected result

### ISSUE THREAD

**Issue by loicgeek** [JonasWanke/rrule#25]
**Describe the bug**

If I try to generate instances with this parameters, I get And unexpected result:
the event starts on 2021-06-17, When I generate instance between  `2021-06-24` and `2021-06-25 ` I still get a result, but that event should occurs only 5 times! So at `2021-06-24` , It should have end up already.
```
var start = DateTime.parse('2021-06-17 19:00:00.000Z');
 var after = DateTime.parse(' 2021-06-24 04:00:00.000Z');
var before = DateTime.parse(' 2021-06-25 03:59:59.000Z');
var rule = RecurrenceRule.fromString("RRULE:FREQ=DAILY;COUNT=5;INTERVAL=1");

```

```
var res = rule
              .getInstances(
                start:start,
                after: after,
                before: before,
                includeAfter: true,
                includeBefore: true,
              )
              .toList();
          print(res);
```

*Output*
`[2021-06-24 19:00:00.000Z]`

**Environment:**

- Package version:  `  rrule: ^0.2.3`

**Comment by JonasWanke** [comment]
Fixed and published as part of [v0.2.8](https://pub.dev/packages/rrule/changelog#028--2022-05-05)
