### ISSUE TITLE
Prefer asserts with message.

### ISSUE THREAD

**Issue by thomassth** [JonasWanke/rrule#28]
**Describe the bug**
Flutter linting is highlighting all asserts with this warning:

> Prefer asserts with message.

It seems they now prefer asserts come with text messages.

https://dart-lang.github.io/linter/lints/prefer_asserts_with_message.html

**Comment by JonasWanke** [comment]
I just updated the lints this package uses ([`34b07a8`](https://github.com/JonasWanke/rrule/commit/34b07a88016d282834fc1961349f2fc1c3fcb476)), but neither before nor after that change did `dart analyze .` or `flutter analyze .` find any issues as `prefer_asserts_with_message` is not activated for this repository. I did, however, add messages to the more complex asserts([`03c8e3d`](https://github.com/JonasWanke/rrule/commit/03c8e3dfc140f2e5d4f956f6a055ecbb7061d5ee)), but don't think that they are necessary for all asserts, as most are self-explanatory.

**Comment by thomassth** [comment]
Can't reproduce now too. Real strange.
