### ISSUE TITLE
Error after upgrading flutter

### ISSUE THREAD

**Issue by pasblin** [JonasWanke/rrule#36]
**Describe the bug**

error logs:

../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/utils.dart:113:48: Error: The property 'firstDayOfMonth' is defined in multiple extensions for 'DateTime' and neither is more specific.
 - 'DateTime' is from 'dart:core'.
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
  DateTime get lastDayOfMonth => plusMonths(1).firstDayOfMonth.subtract(1.days);
                                               ^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/utils.dart:112:16: Context: This is one of the extension members.
  DateTime get firstDayOfMonth => DateTimeRrule(atStartOfDay).copyWith(day: 1);
               ^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/time-2.1.1/lib/src/extensions.dart:217:16: Context: This is one of the extension members.
  DateTime get firstDayOfMonth => isUtc ? DateTime.utc(year, month, 1) : DateTime(year, month, 1);
               ^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/iteration/date_set.dart:89:17: Error: The property 'firstDayOfMonth' is defined in multiple extensions for 'DateTime' and neither is more specific.
 - 'DateTime' is from 'dart:core'.
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
    start: base.firstDayOfMonth.dayOfYear - 1,
                ^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/time-2.1.1/lib/src/extensions.dart:217:16: Context: This is one of the extension members.
  DateTime get firstDayOfMonth => isUtc ? DateTime.utc(year, month, 1) : DateTime(year, month, 1);
               ^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/utils.dart:112:16: Context: This is one of the extension members.
  DateTime get firstDayOfMonth => DateTimeRrule(atStartOfDay).copyWith(day: 1);
               ^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/iteration/date_set.dart:90:15: Error: The property 'lastDayOfMonth' is defined in multiple extensions for 'DateTime' and neither is more specific.
 - 'DateTime' is from 'dart:core'.
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
    end: base.lastDayOfMonth.dayOfYear,
              ^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/time-2.1.1/lib/src/extensions.dart:220:16: Context: This is one of the extension members.
  DateTime get lastDayOfMonth => isUtc ? DateTime.utc(year, month + 1, 0) : DateTime(year, month + 1, 0);
               ^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/utils.dart:113:16: Context: This is one of the extension members.
  DateTime get lastDayOfMonth => plusMonths(1).firstDayOfMonth.subtract(1.days);
               ^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/iteration/date_set_filtering.dart:97:14: Error: The property 'firstDayOfYear' is defined in multiple extensions for 'DateTime' and neither is more specific.
 - 'DateTime' is from 'dart:core'.
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
        date.firstDayOfYear,
             ^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/time-2.1.1/lib/src/extensions.dart:223:16: Context: This is one of the extension members.
  DateTime get firstDayOfYear => isUtc ? DateTime.utc(year, 1, 1) : DateTime(year, 1, 1);
               ^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/utils.dart:108:16: Context: This is one of the extension members.
  DateTime get firstDayOfYear =>
               ^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/iteration/date_set_filtering.dart:98:14: Error: The property 'lastDayOfYear' is defined in multiple extensions for 'DateTime' and neither is more specific.
 - 'DateTime' is from 'dart:core'.
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
        date.lastDayOfYear,
             ^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/time-2.1.1/lib/src/extensions.dart:226:16: Context: This is one of the extension members.
  DateTime get lastDayOfYear => isUtc ? DateTime.utc(year, 12, 31) : DateTime(year, 12, 31);
               ^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/utils.dart:110:16: Context: This is one of the extension members.
  DateTime get lastDayOfYear =>
               ^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/iteration/date_set_filtering.dart:104:14: Error: The property 'firstDayOfMonth' is defined in multiple extensions for 'DateTime' and neither is more specific.
 - 'DateTime' is from 'dart:core'.
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
        date.firstDayOfMonth,
             ^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/time-2.1.1/lib/src/extensions.dart:217:16: Context: This is one of the extension members.
  DateTime get firstDayOfMonth => isUtc ? DateTime.utc(year, month, 1) : DateTime(year, month, 1);
               ^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/utils.dart:112:16: Context: This is one of the extension members.
  DateTime get firstDayOfMonth => DateTimeRrule(atStartOfDay).copyWith(day: 1);
               ^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/iteration/date_set_filtering.dart:105:14: Error: The property 'lastDayOfMonth' is defined in multiple extensions for 'DateTime' and neither is more specific.
 - 'DateTime' is from 'dart:core'.
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
        date.lastDayOfMonth,
             ^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/time-2.1.1/lib/src/extensions.dart:220:16: Context: This is one of the extension members.
  DateTime get lastDayOfMonth => isUtc ? DateTime.utc(year, month + 1, 0) : DateTime(year, month + 1, 0);
               ^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/utils.dart:113:16: Context: This is one of the extension members.
  DateTime get lastDayOfMonth => plusMonths(1).firstDayOfMonth.subtract(1.days);
               ^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/iteration/date_set_filtering.dart:112:12: Error: The property 'firstDayOfMonth' is defined in multiple extensions for 'DateTime' and neither is more specific.
 - 'DateTime' is from 'dart:core'.
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
      date.firstDayOfMonth,
           ^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/time-2.1.1/lib/src/extensions.dart:217:16: Context: This is one of the extension members.
  DateTime get firstDayOfMonth => isUtc ? DateTime.utc(year, month, 1) : DateTime(year, month, 1);
               ^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/utils.dart:112:16: Context: This is one of the extension members.
  DateTime get firstDayOfMonth => DateTimeRrule(atStartOfDay).copyWith(day: 1);
               ^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/iteration/date_set_filtering.dart:113:12: Error: The property 'lastDayOfMonth' is defined in multiple extensions for 'DateTime' and neither is more specific.
 - 'DateTime' is from 'dart:core'.
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
      date.lastDayOfMonth,
           ^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/time-2.1.1/lib/src/extensions.dart:220:16: Context: This is one of the extension members.
  DateTime get lastDayOfMonth => isUtc ? DateTime.utc(year, month + 1, 0) : DateTime(year, month + 1, 0);
               ^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.8/lib/src/utils.dart:113:16: Context: This is one of the extension members.
  DateTime get lastDayOfMonth => plusMonths(1).firstDayOfMonth.subtract(1.days);

**Environment:**

- Package version:

**Comment by FilledStacks** [comment]
Any workarounds for this? Need to get a release out now. I went down to 0.2.7 but it's still breaking.

**Comment by JonasWanke** [comment]
It looks like [<kbd>time</kbd>](https://pub.dev/packages/time) added extensions with conflicting names in [v2.1.1](https://pub.dev/packages/time/changelog#211), so a dependency override should fix this for now:

```yaml
dependency_overrides:
  time: 2.1.0
```

I'll try to release a new version of <kbd>rrule</kbd> using these extensions and removing mine in the next week.

**Comment by FilledStacks** [comment]
@JonasWanke I was gonna comment this as well. Thanks for responding so fast.

**Comment by JonasWanke** [comment]
Fixed in [v0.2.9](https://pub.dev/packages/rrule/changelog#029--2022-06-08)
