### ISSUE TITLE
I cannot build the app since the last update

### ISSUE THREAD

**Issue by loicgeek** [JonasWanke/rrule#37]
**Describe the bug**
 ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.9/lib/src/iteration/date_set.dart:89:17: Error: The getter 'firstDayOfMonth' isn't defined for the class 'DateTime'.
../…/iteration/date_set.dart:89
[        ]  - 'DateTime' is from 'dart:core'.
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'firstDayOfMonth'.
[        ]     start: base.firstDayOfMonth.dayOfYear - 1,

[        ]                 ^^^^^^^^^^^^^^^
[        ] ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.9/lib/src/iteration/date_set.dart:90:15: Error: The getter 'lastDayOfMonth' isn't defined for the class 'DateTime'.
../…/iteration/date_set.dart:90

[        ]  - 'DateTime' is from 'dart:core'.
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'lastDayOfMonth'.
[        ]     end: base.lastDayOfMonth.dayOfYear,
[        ]               ^^^^^^^^^^^^^^
[        ] ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.9/lib/src/iteration/date_set_filtering.dart:97:14: Error: The getter 'firstDayOfYear' isn't defined for the class 'DateTime'.
../…/iteration/date_set_filtering.dart:97

[        ]  - 'DateTime' is from 'dart:core'.
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'firstDayOfYear'.
[        ]         date.firstDayOfYear,
[        ]              ^^^^^^^^^^^^^^

[        ] ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/rrule-0.2.9/lib/src/iteration/date_set_filtering.dart:98:14: Error: The getter 'lastDayOfYear' isn't defined for the class 'DateTime'.
../…/iteration/date_set_filtering.dart:98
[        ]  - 'DateTime' is from 'dart:core'.
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'lastDayOfYear'.
[        ]         date.lastDayOfYear,

**Environment:**
  flutter: 3.0.1
  rrule: ^0.2.9

**Comment by JonasWanke** [comment]
Sorry, I forgot to update the lower bound of the [<kbd>time</kbd>](https://pub.dev/package/time) dependency to [^2.1.1](https://pub.dev/packages/time/changelog#211) in the previous release. This is now fixed in [v0.2.10](https://pub.dev/packages/rrule/changelog#0210--2022-06-17) (commit: [`8755f27`](https://github.com/JonasWanke/rrule/commit/8755f277c23479c3d789dbc331ed84e6824f9b3d))
