### ISSUE TITLE
Convert String rrule to RecurrenceRule

### ISSUE THREAD

**Issue by fabads** [JonasWanke/rrule#4]
Hello,

I store rrule events as strings in Firestore. Is there any simple way to convert strings to RecurrenceRule objects. I saw in your documentation that you can convert a RecurrenceRule to string but did not see the opposite.

Fabrice

**Comment by fabads** [comment]
Forget my request, I checked your code and you had the great idea to implement RecurrenceRule.fromString(input string)
Excellent library, it really helps!

**Comment by JonasWanke** [comment]
Thanks a lot for your feedback! Correct, you can parse it via [`RecurrenceRule.fromString()`](https://pub.dev/documentation/rrule/latest/rrule/RecurrenceRule/RecurrenceRule.fromString.html) as you already discovered, or use the underlying [`RecurrenceRuleStringCodec`](https://pub.dev/documentation/rrule/latest/rrule/RecurrenceRuleStringCodec-class.html) directly.

I just fixed the example shown in the README and will think about improving it in general soon.

**Comment by fabads** [comment]
Many thanks for your feedback! Just a question (ok maybe stupid) why did
you time_machine? I just need to play with day recurrence, I noticed that
it was not necessary to initialize this package but had to convert
LocalDayTime to DateTime (Var types used in my code).

Best Regards.

Fabrice

Le dim. 31 mai 2020 à 17:53, Jonas Wanke <notifications@github.com> a
écrit :

**Comment by JonasWanke** [comment]
I really like the clean separation of types like `LocalDateTime` as a calendar concept as opposed to `Instant` representing a single point in time or `ZonedDateTime` as a point in time in a specific time zone. It might not be necessary for this package, but I'm already using it in my other projects as well, (mostly) like its API and it also explicitly states that this package doesn't handle time zones by itself.

I'll probably add a section to the README at some point briefly explaining <kbd>time_machine</kbd> and how to use it with Dart's native `DateTime`.

**Comment by fabads** [comment]
Thanks for these explanations. I'm still struggling to filter my instances
and I'm wondering if it could be an issue with date conversion.

void _buildEventsList(List<Program> programs) {
  _events.clear();
  programs.forEach((program) {
    RecurrenceRule rrule = RecurrenceRule.fromString(program.rrule);
    print("Program: $program");
    final Iterable<LocalDateTime> instances = rrule.getInstances(
        start: LocalDateTime.dateTime(program.dtstart.toDate()));

    print("Calendar dates: $_calendarDateFirst, $_calendarDateLast");

    final inFrame = instances.where((instance) =>
    instance.toDateTimeLocal().compareTo(_calendarDateFirst) >= 0 &&
        instance.toDateTimeLocal().compareTo(_calendarDateLast) <= 0);

    inFrame.forEach((event) {
      print("Processing event :$event");
    });
  });
}

My table_calendar is calling a callback with first & last visible date
(when created or when user selects other dates). Then I get relevant
instances comprised in this date window.
Finally I processing each event. The code is crashing in the
inFrame.forEach loop, it seems never ending.

Here the log:
I/flutter ( 3066): Program: id: 316624, name: test, rrule:
RRULE:FREQ=DAILY;INTERVAL=1, dtstart: Timestamp(seconds=1590216018,
nanoseconds=317582000)
I/flutter ( 3066): Calendar dates: 2020-06-01 12:00:00.000Z, 2020-06-30
12:00:00.000Z
I/flutter ( 3066): Processing event :06/02/2020 06:40:18
I/flutter ( 3066): Processing event :06/03/2020 06:40:18
I/flutter ( 3066): Processing event :06/04/2020 06:40:18
I/flutter ( 3066): Processing event :06/05/2020 06:40:18
I/flutter ( 3066): Processing event :06/06/2020 06:40:18
I/flutter ( 3066): Processing event :06/07/2020 06:40:18
I/flutter ( 3066): Processing event :06/08/2020 06:40:18
I/flutter ( 3066): Processing event :06/09/2020 06:40:18
I/flutter ( 3066): Processing event :06/10/2020 06:40:18
I/flutter ( 3066): Processing event :06/11/2020 06:40:18
I/flutter ( 3066): Processing event :06/12/2020 06:40:18
I/flutter ( 3066): Processing event :06/13/2020 06:40:18
I/flutter ( 3066): Processing event :06/14/2020 06:40:18
I/flutter ( 3066): Processing event :06/15/2020 06:40:18
I/flutter ( 3066): Processing event :06/16/2020 06:40:18
I/flutter ( 3066): Processing event :06/17/2020 06:40:18
I/flutter ( 3066): Processing event :06/18/2020 06:40:18
I/flutter ( 3066): Processing event :06/19/2020 06:40:18
I/flutter ( 3066): Processing event :06/20/2020 06:40:18
I/flutter ( 3066): Processing event :06/21/2020 06:40:18
I/flutter ( 3066): Processing event :06/22/2020 06:40:18
I/flutter ( 3066): Processing event :06/23/2020 06:40:18
I/flutter ( 3066): Processing event :06/24/2020 06:40:18
I/flutter ( 3066): Processing event :06/25/2020 06:40:18
I/flutter ( 3066): Processing event :06/26/2020 06:40:18
I/flutter ( 3066): Processing event :06/27/2020 06:40:18
I/flutter ( 3066): Processing event :06/28/2020 06:40:18
I/flutter ( 3066): Processing event :06/29/2020 06:40:18
I/flutter ( 3066): Processing event :06/30/2020 06:40:18

And after a long moment, I get this error: RangeError: Date computation
would overflow the maximum year of the calendar.

Do you have an idea where my error could be?
Regards.

Fabrice



Le dim. 31 mai 2020 à 18:36, Jonas Wanke <notifications@github.com> a
écrit :

**Comment by JonasWanke** [comment]
The problem is your filtering:

```dart
final inFrame = instances.where((instance) =>
    instance.toDateTimeLocal().compareTo(_calendarDateFirst) >= 0 &&
    instance.toDateTimeLocal().compareTo(_calendarDateLast) <= 0);
```

The `Iterable` returned by <kbd>rrule</kbd> is infinite if the rule doesn't contain an `UNTIL` or `COUNT` part. The returned instances are sorted, but `where` will always fetch a new instance not knowing that none will match anymore. An example in the README shows how to use `takeUntil` to avoid this problem. Applied to your code it looks like the following:

```dart
final inFrame = instances
  // Ignore instances that happen to early.
  .where((instance) => instance.toDateTimeLocal().compareTo(_calendarDateFirst) >= 0)
  // And end when the first instance is after our relevant end.
  .takeWhile((instance) => instance.toDateTimeLocal().compareTo(_calendarDateLast) <= 0);
```
<sup>(Not tested, but this should work.)</sup>

> **Note:** I will soon add convenience parameters to simplify this part.

**Comment by fabads** [comment]
Many thanks, I think you saved my day, just tested your proposal and it
works like a charm. What you developed was really missing to flutter
packages library.
I'm doing a DYI irrigation controller and your package really eases my life
to manage start of watering programs.
Fabrice


Le lun. 1 juin 2020 à 09:21, Jonas Wanke <notifications@github.com> a
écrit :

**Comment by JonasWanke** [comment]
Thank you so much and have fun with your project :)
