### ISSUE TITLE
Package doesn't allow to use intl v0.18

### ISSUE THREAD

**Issue by TatsuUkraine** [JonasWanke/rrule#45]
**Describe the bug**
Most recent version of intl is 0.18. RRule package doesn't allow to use it. Trying to install most up to date version on intl leads to an error
`Because rrule 0.2.10 depends on intl ^0.17.0 and no versions of rrule match >0.2.10 <0.3.0, rrule ^0.2.10 requires intl ^0.17.0.`

**Environment:**
- Package version:  0.2.10

**Comment by JonasWanke** [comment]
Fixed in [v0.2.11](https://pub.dev/packages/rrule/changelog#0211--2023-01-24)
