### ISSUE TITLE
intl should be reverted to v0.17.0 until Flutter stable supports v0.18.0

### ISSUE THREAD

**Issue by absar** [JonasWanke/rrule#51]
**Describe the bug**
We cannot use `rrule 0.2.11` or `0.2.12` with Flutter stable 3.7.7, since Flutter usually pins the dependency on `intl` currently it is 0.17. Hence ideally this package and any other packages should follow flutter.
The issue: `Because App depends on flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required. So, because App depends on intl ^0.18.0, version solving failed`, the 0.18.0 in error is due to `rrule` using `intl 0.18.0`
Unfortunately we cannot use `rrule 0.2.10` since `rrule 0.2.12` has a bug fix.

**Environment:**

- Package version:  rrule: ^0.2.12
- Flutter: Channel stable, 3.7.7

**Comment by JonasWanke** [comment]
The new release [v0.2.13](https://pub.dev/packages/rrule/changelog#0213--2023-03-22) widened the <kbd>intl</kbd> dependency to `>=0.17.0 <0.19.0` so that <kbd>rrule</kbd> should work fine with both Flutter stable and beta
