### ISSUE TITLE
It cannot parse its own strings when current locale does not use Latin numbers

### ISSUE THREAD

**Issue by absar** [JonasWanke/rrule#59]
When an RRule is created from locales other than the ones with Latin numbers `rrule.toString` generates the string in localized numerals for `UNTIL` date, which is not right, since rrule cannot parse back the localized string to RRule, this is due to the fact that `iCalDateTimePattern` is using `intl.DateFormat.format` and then tries to parse back using simple `DateTime.tryParse` which is not aware of locale.

It has another issue `iCalDateTimePattern` is defined as a global final, which means once initialized it will capture current locale, if user changes the locale from App, rrule will not change the date/time format until the app is fully closed and reopened.

Fix would be to manually create the `toString` instead of using `intl.DateFormat.format`, like how dart does in `toIso8601String` to produce ISO-8601 compliant strings

Code to reproduce the issue:
Instead of generating `RRULE:FREQ=DAILY;UNTIL=19971224T000000` it generates Arabic `RRULE:FREQ=DAILY;UNTIL=١٩٩٧١٢٢٤T٠٠٠٠٠٠`, then it's unable to parse back the generated string:

``` dart
import 'package:intl/intl.dart';
import 'package:rrule/rrule.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:intl/date_symbol_data_local.dart';

void main() async {
  Intl.defaultLocale = 'ar';
  await initializeDateFormatting();

  group('arabic', () {
    test('arabic', () {
      final rrule = RecurrenceRule(frequency: Frequency.daily, until: DateTime.utc(1997, 12, 24));
      final string = rrule.toString();
      print(string);
      // expect(string, 'RRULE:FREQ=DAILY;UNTIL=19971224T000000');

      final fromString = RecurrenceRule.fromString(string);
      expect(fromString, rrule);
    });
  });
}

```

- Package version:  rrule 0.2.13

**Comment by JonasWanke** [comment]
This is fixed as part of [v0.2.14](https://pub.dev/packages/rrule/changelog#0214--2023-09-13)
