### ISSUE TITLE
Counting of interval starts from 'after' and not from 'start'

### ISSUE THREAD

**Issue by tkortekaas** [JonasWanke/rrule#71]
```
final rule = RecurrenceRule.fromString('RRULE:FREQ=WEEKLY;INTERVAL=2;BYDAY=SU');
print(rule.getInstances(start: DateTime.utc(2024, 2, 7))); // (2024-02-11 00:00:00.000Z, 2024-02-25 00:00:00.000Z, ...)
print(rule.getInstances(start: DateTime.utc(2024, 2, 7), after: DateTime.utc(2024, 2, 12))); // (2024-02-18 00:00:00.000Z, 2024-03-03 00:00:00.000Z, ...)
```
The example above explains my issue. When I set a biweekly event to start on February 7th and to repeat every week on Sunday, I would expect the event to be repeated on (2024-02-11 00:00:00.000Z, 2024-02-25 00:00:00.000Z, ...) as indicated by the first print.
However, for performance reasons, I would now like to get all events from February 12th onwards, because the starting event might actually be many weeks in the past and I don't want to iterate over all of the intermediate occurrences. Now, however, the first date is not the 2024-02-25 00:00:00.000Z as I expect, but 2024-02-18 00:00:00.000Z. This makes it so that for my purposes, events with FREQ=WEEKLY;INTERVAL=2 always show this event on Sunday. 

Is this a bug or is this defined like this in the iCalendar RFC?

I really love the package by the way, thanks so much!!!

**Comment by JonasWanke** [comment]
Thanks for filing the issue! This is an edge case we overlooked in a recent performance improvement (#66). It's fixed as part of [v0.2.16](https://pub.dev/packages/rrule/changelog#0216--2024-02-07)
