### ISSUE TITLE
byweekdays feature not working 

### ISSUE THREAD

**Issue by shankarbhattarai123** [JonasWanke/rrule#76]
When implementing rrule in flutter application byweekdays feature is not working.

**Comment by JonasWanke** [comment]
Can you please clarify what you mean by not working? Please include some code and explain what you expect it to do.

**Comment by shankarbhattarai123** [comment]
`void generateAndScheduleNotifications() {
    hiveController.retrieveCustomMinute();
    DateTime start = convertTimeOfDayToDateTime(startTime).toUtc();
    print('Generating daily notifications...$selectedDayNames');
    final rule = RecurrenceRule(
        frequency: Frequency.daily,
        until: start.add(Duration(days: 730)),
        byWeekDays: [
          ByWeekDayEntry(DateTime.tuesday),
          ByWeekDayEntry(DateTime.thursday),
        ]);

    final instances = rule
        .getInstances(
            start: DateTime.utc(start.year, start.month, start.day, start.hour,
                start.minute, start.second))
        .toList();

    final dates = instances
        .map((instance) =>
            tz.TZDateTime.from(instance, tz.getLocation('Asia/Kathmandu')))
        .toList();
    print('daily Dates to schedule: ${dates}');
    _scheduleDailyAndMinutelyNotifications(dates);
  }`
@JonasWanke In above code notification is scheduled for only tuesday and thursday but notification is scheduled for others day also
