### ISSUE TITLE
Why you are using LocalDateTime instead of DateTime?

### ISSUE THREAD

**Issue by polRk** [JonasWanke/rrule#9]
I have great difficulties when I write and run unit tests. 
```
Unsupported operation: Isolate.resolvePackageUri
```

**Comment by JonasWanke** [comment]
[v0.2.0](https://github.com/JonasWanke/rrule/releases/tag/v0.2.0) no longer uses [<kbd>time_machine</kbd>](https://pub.dev/packages/time_machine), but Dart's `DateTime` instead.
